module.exports = {
  // Global App actions
  //INIT_SESSION: 'INIT_SESSION',
  // SET_GENERAL_ERROR: 'SET_GENERAL_ERROR',
  // CLEAR_GENERAL_ERROR: 'CLEAR_GENERAL_ERROR',

  // Setting
  GET_META_DATA: 'GET_META_DATA',
  GET_SETTING_APP: 'GET_SETTING_APP',
  FINISH_INIT_APP: 'FINISH_INIT_APP',
  START_APP_LOADING: 'START_APP_LOADING',
  STOP_APP_LOADING: 'STOP_APP_LOADING',
  SET_LAST_LOCATION_TIME: 'SET_LAST_LOCATION_TIME', //Show Test
  SET_LOCATION_TRACKING: 'SET_LOCATION_TRACKING',
  SET_LOCATION_TRACKING_DONE: 'SET_LOCATION_TRACKING_DONE',

  //Login
  SET_LOGIN_PENDING: 'SET_LOGIN_PENDING',
  LOGIN_SUCCESSFULLY: 'LOGIN_SUCCESSFULLY',
  RESET_AUTHENTICATION: 'RESET_AUTHENTICATION',
};
